services:

  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     MIX_ENV: dev
  #   platform: linux/amd64
  #   container_name: manager_dev
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - db
  #   volumes:
  #     - .:/opt/app

  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manager_dev
    volumes:
      - data:/data/db

volumes:
  data:
